theme: jekyll-theme-cayman
title: "Debugging Machine Learning Models"
description: 
- ICLR 2019 workshop, May 6, 2019, New Orleans
- 9.50am - 6.30pm, Room R03
buttons:
  Speakers: '#speakers'
  Schedule: '#schedule'
  Posters: '#posters'
  Demos: '#demos'
  Organizers: '#organizers'
